version: '3.8'
services:
  qbittorrent: # mp下载的qb
    image: linuxserver/qbittorrent:4.6.4
    container_name: qbittorrent
    restart: always
    volumes:
      - ${DOCKER_ROOT_PATH}/qBittorrent/config:/config
      - ${VIDEO_ROOT_PATH}:/media
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      UMASK: ${UMASK}
      TZ: Asia/Shanghai
      WEBUI_PORT: 8080
      SavePatch: /media/downloads
      TempPatch: /media/downloads
    networks:
      eth1:
        ipv4_address: 10.10.10.8
  qbittorrent-seed: # mp刷流的qb
    image: linuxserver/qbittorrent:4.6.4
    container_name: qbittorrent-seed
    restart: always
    volumes:
      - ${DOCKER_ROOT_PATH}/qbittorrent/config:/config
      - ${SEED_ROOT_PATH}/刷流:/seed
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      UMASK: ${UMASK}
      TZ: Asia/Shanghai
      WEBUI_PORT: 8080
      SavePatch: /seed
      TempPatch: /seed
    networks:
      eth1:
        ipv4_address: 10.10.10.22  # 替换为指定的 IP 地址
#  emby:
#    image: emby/embyserver:latest
#    container_name: emby
#    restart: always
#    volumes:
#      - ${DOCKER_ROOT_PATH}/emby:/config
#      - ${VIDEO_ROOT_PATH}:/media
#    environment:
#      PUID: ${PUID}
#      PGID: ${PGID}
#      UMASK: ${UMASK}
#      TZ: Asia/Shanghai
#    devices:
#      - /dev/dri:/dev/dri
#    networks:
#      eth1:
#        ipv4_address: 10.10.10.6  # 替换为指定的 IP 地址

  chinese-sub-finder:
    image: allanpk716/chinesesubfinder:latest
    container_name: chinese-sub-finder
    restart: always
    volumes:
      - ${DOCKER_ROOT_PATH}/chinese-sub-finder/config:/config
      - ${DOCKER_ROOT_PATH}/chinese-sub-finder/cache:/app/cache
      - ${VIDEO_ROOT_PATH}:/media
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      UMASK: ${UMASK}
      TZ: Asia/Shanghai
    networks:
      eth1:
        ipv4_address: 10.10.10.16  # 替换为指定的 IP 地址

  moviepilot:
    image: jxxghp/moviepilot-v2:latest
    container_name: moviepilot-v2
    restart: always
    privileged: true
    volumes:
      - ${VIDEO_ROOT_PATH}:/media
      - ${DOCKER_ROOT_PATH}/moviepilot-v2/config:/config
      - ${DOCKER_ROOT_PATH}/moviepilot-v2/core:/moviepilot/.cache/ms-playwright
      # - ${DOCKER_ROOT_PATH}/qb-seed/config/qBittorrent/BT_backup:/qbtr
    environment:
      MOVIEPILOT_AUTO_UPDATE: release
      PUID: ${PUID}
      PGID: ${PGID}
      UMASK: ${UMASK}
      TZ: Asia/Shanghai
      AUTH_SITE: leaves
      LEAVES_UID: 10971
      LEAVES_PASSKEY: e0405a9d0de9e3b112ef78ac3d9c7975
      SUPERUSER: admin
      API_TOKEN: nasptnasptnasptnaspt
      PROXY_HOST: http://naspt:naspt@10.10.10.2:7890
    networks:
      eth1:
        ipv4_address: 10.10.10.7

  owjdxb:
    image: ionewu/owjdxb
    container_name: ddns
    restart: always
    volumes:
      - ${DOCKER_ROOT_PATH}/store:/data/store
    networks:
      eth1:
        ipv4_address: 10.10.10.10  # 替换为指定的 IP 地址

networks:
  eth1:
    external: true